language: ruby
rvm:
  - 2.4.3
env:

before_script:
  - psql -c "CREATE USER marvel_minds WITH PASSWORD 'stephen';" -U postgres
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
services:
  - postgresql
notifications:
  email: false
