default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: marvel_minds_development
  pool: 5
  username: marvel_minds
  password: <%= ENV['MARVEL_MINDS_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: marvel_minds_test
  pool: 5
  username: marvel_minds
  password: <%= ENV['MARVEL_MINDS_PASSWORD'] %>

production:
  <<: *default
  database: marvel_minds_production
  username: marvel_minds
  password: <%= ENV['MARVEL_MINDS_PASSWORD'] %>
